name: $(Date:yyyyMMdd)$(Rev:.r)
pool:
  vmImage: "windows-latest"
jobs:
- job: Build
  steps:
  - task: gitversion/setup@0
    inputs:
      versionSpec: '5.x'
  - task: gitversion/execute@0
    displayName: "Update SharedAssemblyInfo version"
    inputs:
      useConfigFile: true
      configFilePath: 'GitVersion.yml'
      additionalArguments: '/updateassemblyinfo .\src\SharedAssemblyInfo.cs'
  - task: gitversion/execute@0
    displayName: "Update dotnet csproj assembly version"
    inputs:
      targetPath: '$(Build.SourcesDirectory)'
      useConfigFile: true
      configFilePath: 'GitVersion.yml'
      additionalArguments: '/updateprojectfiles'
  - task: DotNetCoreCLI@2
    displayName: "Dotnet Restore"
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: 'NuGet.config'
  - task: DotNetCoreCLI@2
    displayName: "Build"
    inputs:
      command: 'build'
      arguments: --no-restore -c "Release"
  - task: DotNetCoreCLI@2
    displayName: "Dotnet Pack"
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'GitVersion.NuGetVersion'
      includeSymbols: true
      nobuild: true
  - task: DotNetCoreCLI@2
    # condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/')))
    displayName: "Push to Artifact feed"
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '8e7d8e9a-96b7-4364-985a-625841ad216e/f096d8c4-c6ef-4c3f-ab64-f47f1c625b2e'
      arguments: --no-symbols
  - task: PublishPipelineArtifact@1
    displayName: "Publish Build Artifact"
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: Packages
    