name: $(Date:yyyyMMdd)$(Rev:.r)
pool:
  vmImage: "windows-latest"
jobs:
- job: Build
  steps:
  - task: GitVersion@5
    inputs:
      runtime: 'core'
      configFilePath: 'GitVersion.yml'
      updateAssemblyInfo: true
      updateAssemblyInfoFilename: 'src/SharedAssemblyInfo.cs'
  - task: DotNetCoreCLI@2
    displayName: "NuGet Restore"
    inputs:
      command: 'restore'
      feedsToUse: 'config'
      nugetConfigPath: 'NuGet.config'
  - task: DotNetCoreCLI@2
    displayName: "Build"
    inputs:
      command: 'build'
      arguments: --no-restore -c "Release"
  - task: DotNetCoreCLI@2
    displayName: "Dotnet Pack"
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'GitVersion.NuGetVersion'
      includeSymbols: true
      nobuild: true
  - task: DotNetCoreCLI@2
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    displayName: "Push to Artifact feed"
    inputs:
      command: 'push'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'Leprechaun'
  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))
    displayName: "Publish Build Artifact"
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: Packages
    